# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launding', '0002_auto_20170301_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='ip',
            new_name='ipadress',
        ),
    ]
