# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launding', '0008_poll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
